# Notebook Imports

In [1]:
from numpy.random import seed
seed(888)
from tensorflow import set_random_seed 
set_random_seed(404)

/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passi

In [112]:
import os
import numpy as np
import tensorflow as tf

from time import strftime

from PIL import Image

# Constants

In [3]:
IMAGE_HEIGHT = 28
IMAGE_WIDTH = 28
NR_CHANNELS = 1
TOTAL_INPUTS = IMAGE_HEIGHT * IMAGE_WIDTH * NR_CHANNELS

NR_CLASSES = 10
VALIDATION_SIZE = 10000


LOGGING_PATH = 'tensorboard_mnist_digit_logs/'

# Get the data

In [4]:
(x_train_all, y_train_all) , (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Explore and preprocess the data

In [5]:
x_train_all.shape #60,000 images, 28 x 28 pixels

(60000, 28, 28)

In [6]:
y_train_all.shape #60,000 classification labels

(60000,)

In [7]:
x_test.shape #10,000 images, 28 x 28 pixels

(10000, 28, 28)

In [8]:
y_test.shape #10,000 image classification labels

(10000,)

In [9]:
x_train_all[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [10]:
y_train_all[0]

5

In [11]:
y_train_all[:6]

array([5, 0, 4, 1, 9, 2], dtype=uint8)

In [12]:
type(x_train_all[0][0][0])

numpy.uint8

In [13]:
#convert to float
x_train_all = x_train_all / 255.0
type(x_train_all[0][0][0])

numpy.float64

In [14]:
x_test = x_test / 255.0
type(x_test[0][0][0])

numpy.float64

In [15]:
# reshape the data
x_train_all = x_train_all.reshape(x_train_all.shape[0], TOTAL_INPUTS)
x_train_all.shape

(60000, 784)

In [16]:
x_test = x_test.reshape(x_test.shape[0], TOTAL_INPUTS)
x_test.shape

(10000, 784)

### One Hot Encoding

In [17]:
np.eye(NR_CLASSES)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.eye(NR_CLASSES)[5]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [19]:
np.eye(NR_CLASSES)[9]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [20]:
np.eye(NR_CLASSES)[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.eye(NR_CLASSES)[[0, 3, 5]]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [22]:
y_test = np.eye(NR_CLASSES)[y_test]
y_test.shape

(10000, 10)

In [23]:
y_train_all = np.eye(NR_CLASSES)[y_train_all]
y_train_all.shape

(60000, 10)

### Create a validation dataset from the training data

In [24]:
x_val = x_train_all[:VALIDATION_SIZE]
y_val = y_train_all[:VALIDATION_SIZE]
print(x_val.shape, y_val.shape)

(10000, 784) (10000, 10)


In [25]:
x_train = x_train_all[VALIDATION_SIZE:]
y_train = y_train_all[VALIDATION_SIZE:]
print(x_train.shape, y_train.shape)

(50000, 784) (50000, 10)


# Set up tensorflow graph

In [162]:
X = tf.placeholder(dtype=tf.float32, shape = [None, TOTAL_INPUTS], name = 'Features') 
Y = tf.placeholder(dtype=tf.float32, shape = [None, NR_CLASSES], name = 'Labels')

### Neural Network Architecture

### Hyperparamters

In [163]:
nr_epochs = 50 #number of times to pass through the network
learning_rate = 0.0001 #value to multiply by during gradient descent / model optimization

#number of nuerons per layer
n_hidden1 = 512
n_hidden2 = 64

In [164]:
def setup_layer(input_features, weight_dim, bias_dem, name):
    
    with tf.name_scope(name):
        
        #weight
        initial_w = tf.truncated_normal(shape=weight_dim, stddev=0.1, seed = 42)
        w = tf.Variable(initial_value=initial_w, name='W')

        #bias
        initial_b = tf.constant(value=0.0, shape=bias_dem)
        b = tf.Variable(initial_value=initial_b, name='B')

        #input
        layer_in = tf.matmul(input_features, w) + b
        
        #track weights and biases
        tf.summary.histogram(name='weights', values=w)
        tf.summary.histogram(name='biases', values=b)   

        #output
        if name == 'out':
            layer_out = tf.nn.softmax(layer_in)
        else:
            layer_out = tf.nn.relu(layer_in)
            
    return layer_out

In [165]:
#without dropout layer
# layer_1 = setup_layer(input_features=X, weight_dim=[TOTAL_INPUTS, n_hidden1], 
#                       bias_dem=[n_hidden1], name='layer_1')

# layer_2 = setup_layer(input_features=layer_1, weight_dim=[n_hidden1, n_hidden2], 
#                       bias_dem=[n_hidden2], name='layer_2')

# output = setup_layer(input_features=layer_2, weight_dim=[n_hidden2, NR_CLASSES], 
#                       bias_dem=[NR_CLASSES], name='out')

# model_name = f'{n_hidden1}-{n_hidden2} E{nr_epochs} LR{learning_rate}'

In [166]:
layer_1 = setup_layer(input_features=X, weight_dim=[TOTAL_INPUTS, n_hidden1], 
                      bias_dem=[n_hidden1], name='layer_1')

layer_drop = tf.nn.dropout(layer_1, keep_prob=0.8, name = 'dropout_layer')

layer_2 = setup_layer(input_features=layer_drop, weight_dim=[n_hidden1, n_hidden2], 
                      bias_dem=[n_hidden2], name='layer_2')

output = setup_layer(input_features=layer_2, weight_dim=[n_hidden2, NR_CLASSES], 
                      bias_dem=[NR_CLASSES], name='out')

model_name = f'{n_hidden1}-DO-{n_hidden2} E{nr_epochs} LR{learning_rate}'

# Tensorboard setup

In [167]:
folder_name = f'{model_name} at {strftime("%H:%M")}'
directory = os.path.join(LOGGING_PATH, folder_name)

try:
    os.makedirs(directory)
except OSError as os_exception:
    print(os_exception.strerror)
else:
    print('Successfully created directories')

Successfully created directories


# Loss, Optimisation and Accuracy

#### Loss

In [168]:
with tf.name_scope('loss_calculation'):
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels = Y, logits = output))

#### Define the optimizer

In [169]:
with tf.name_scope('optimizer'):
    optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)
    train_step = optimizer.minimize(loss)

#### Accuracy

In [170]:
with tf.name_scope('accuracy_calc'):
    correct_pred = tf.equal(tf.arg_max(output, dimension=1), tf.argmax(Y, dimension=1)) 
    accuracy = tf.reduce_mean(tf.cast(correct_pred, dtype=tf.float32))

with tf.name_scope('performace'):
    tf.summary.scalar(name='accuracy',tensor=accuracy) # create summary - accuracy
    tf.summary.scalar(name='loss', tensor=loss)

#### Check input images in tensorboard

In [171]:
with tf.name_scope('show_image'):
    x_image = tf.reshape(tensor=X, shape=[-1, 28, 28, 1])
    tf.summary.image('image_input',x_image, max_outputs=4)

# Run Session

In [172]:
sesh = tf.Session()

### Setup filewriter and merge summaries

In [173]:
#merge all summaries
merged_summary = tf.summary.merge_all()

#set up filewriter - to write the summaries to a file
train_writer = tf.summary.FileWriter(logdir=directory + '/train')

#tell the filewriter which calculations to write to file
train_writer.add_graph(sesh.graph)


#validation writer
validation_writer = tf.summary.FileWriter(logdir=directory + '/validation')

### initialize all variables

In [174]:
init = tf.global_variables_initializer()

sesh.run(init)

## Batching the data

In [175]:
size_of_batch = 1000
num_examples = y_train.shape[0]

nr_interations = int(num_examples / size_of_batch)

index_in_epoch = 0

In [176]:
def next_batch(batch_size, data, labels):
    global num_examples
    global index_in_epoch
    
    start = index_in_epoch
    index_in_epoch += batch_size
    
    if index_in_epoch > num_examples: #start the next epoch
        start = 0
        index_in_epoch = batch_size
    
    end = index_in_epoch
    
    return data[start:end] , labels[start:end]

## Training loop

In [177]:
for epoch in range(nr_epochs):
    
    # =================== Training Data =======================
    for i in range(nr_interations):
        
        batch_x , batch_y = next_batch(batch_size = size_of_batch, data = x_train, labels = y_train)
        
        #create a feed dictionary to feed to the session
        feed_dictionary = {X:batch_x, Y:batch_y}
        
        #feed dictionary to session
        sesh.run(train_step, feed_dict=feed_dictionary)
        
    #calculate accuracy
    summary , batch_accuracy = sesh.run(fetches=[merged_summary, accuracy], feed_dict = feed_dictionary)
    
    #write summary each epoch to disk
    train_writer.add_summary(summary, epoch)
    
    print(f'Epoch {epoch} \t accuracy: {batch_accuracy}')
    
    # ======================== Validation data =====================
    validation_summary = sesh.run(fetches=merged_summary, feed_dict = {X:x_val, Y:y_val})
    
    validation_writer.add_summary(validation_summary, epoch)
    
    
print('Training complete!')

Epoch 0 	 accuracy: 0.37700000405311584
Epoch 1 	 accuracy: 0.6990000009536743
Epoch 2 	 accuracy: 0.7940000295639038
Epoch 3 	 accuracy: 0.8259999752044678
Epoch 4 	 accuracy: 0.8399999737739563
Epoch 5 	 accuracy: 0.8460000157356262
Epoch 6 	 accuracy: 0.8479999899864197
Epoch 7 	 accuracy: 0.8560000061988831
Epoch 8 	 accuracy: 0.8539999723434448
Epoch 9 	 accuracy: 0.8619999885559082
Epoch 10 	 accuracy: 0.859000027179718
Epoch 11 	 accuracy: 0.8619999885559082
Epoch 12 	 accuracy: 0.8610000014305115
Epoch 13 	 accuracy: 0.8560000061988831
Epoch 14 	 accuracy: 0.8659999966621399
Epoch 15 	 accuracy: 0.8640000224113464
Epoch 16 	 accuracy: 0.8619999885559082
Epoch 17 	 accuracy: 0.8629999756813049
Epoch 18 	 accuracy: 0.8619999885559082
Epoch 19 	 accuracy: 0.8629999756813049
Epoch 20 	 accuracy: 0.8659999966621399
Epoch 21 	 accuracy: 0.8659999966621399
Epoch 22 	 accuracy: 0.8690000176429749
Epoch 23 	 accuracy: 0.8659999966621399
Epoch 24 	 accuracy: 0.8700000047683716
Epoch 25 	

# Make a prediction

In [178]:
img = Image.open('MNIST/test_img.png')
img

In [179]:
#convert to black and white
bw = img.convert("L")

In [180]:
#create an array of inverted values
inverted_img_array = np.invert(bw)
inverted_img_array.shape

(28, 28)

In [181]:
#flatten
flat_image = inverted_img_array.ravel()
flat_image.shape

(784,)

In [182]:
#make prediction
prediction = sesh.run(fetches=tf.argmax(output, axis=1), feed_dict={X:[flat_image]})
print(f'Prediction for test image is: {prediction}')

Prediction for test image is: [2]


# Testing and Evaluation

In [183]:
#test on the test data set and calculate accuracy
accuracy = sesh.run(fetches=accuracy, feed_dict={X:x_test, Y:y_test})

In [194]:
print(f'Accuracy on the testing data set is: {accuracy:0.3%}')

Accuracy on the testing data set is: 94.660%


# Reset for the next run

In [184]:
train_writer.close()
validation_writer.close()
sesh.close()
tf.reset_default_graph()

### First tries

In [185]:
# with tf.name_scope('first_hidden_layer'): #group the following opperations for tensorboard viz
    
#     #Set the initial weights between inputs and hidden layer 1
#     initial_w1 = tf.truncated_normal(shape=[TOTAL_INPUTS, n_hidden1], stddev=0.1, seed = 42)
#     w1 = tf.Variable(initial_value = initial_w1, name='w1')

#     #set the initial bias between input and layer1
#     initial_b1 = tf.constant(value=0.0, shape =[n_hidden1])
#     b1 = tf.Variable(initial_value = initial_b1, name='b1')

#     # the initial inputs to hidden layer 1 = to input x hidden 1
#     layer1_in = tf.matmul(X, w1) + b1

#     # the ouput will depend on the input and the activation function
#     layer1_out = tf.nn.relu(layer1_in)

In [186]:
# with tf.name_scope('second_hidden_layer'):

#     # set up weights, biases, outputs for layer 2
#     initial_w2 = tf.truncated_normal(shape=[n_hidden1, n_hidden2], stddev=0.1, seed = 42)
#     w2 = tf.Variable(initial_value = initial_w2, name='w2')

#     #bias
#     initial_b2 = tf.constant(value=0.0, shape=[n_hidden2])
#     b2 = tf.Variable(initial_value = initial_b2, name='b2')

#     #
#     layer2_in = tf.matmul(layer1_out, w2) + b2

#     layer2_out = tf.nn.relu(layer2_in)

In [187]:
# with tf.name_scope('output_layer'):

#     #layer2 to output
#     initial_w_o = tf.truncated_normal(shape=[n_hidden2, NR_CLASSES], stddev=0.1, seed = 42)
#     w_o = tf.Variable(initial_value = initial_w_o, name='w3')

#     #bias
#     initial_b_o = tf.constant(value=0.0, shape=[NR_CLASSES])
#     b_o = tf.Variable(initial_value = initial_b_o, name='b3')

#     #
#     output_layer_in = tf.matmul(layer2_out, w_o) + b_o

#     output_layer_out = tf.nn.softmax(output_layer_in)

In [188]:
#w1.eval(sesh)

In [189]:
#b_o.eval(sesh)